# Generated by Django 4.1.4 on 2022-12-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=150)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
